### PR TITLE
Feature cleanup and update

### LINKED ISSUE #1: 404 after translating url segment
Hi @Internetrix,
thank you for your plugin it helped me to fight against row size too large issue but I have another problem. After installing your module I get 404 after translating url segment as well as default fields such as Page Name or Navigation label doesn't have that orange indicator after actual translation. Is there a quick (or any) fix for this? 

Thanks,
D.

### PR DESCRIPTION
**Pull request by xini**
- clean up code
- add support for isFieldNullable
- fix CMS labels for modified fields
- fixes #1

### CODE REVIEW

**Comment by jason-zz** [comment]
Thank you @xini ! I'm going to merge your PR. Cheers.

**Comment by xini** [comment]
thanks @jason-zz , can you please tag a release with this? cheers

**Comment by jason-zz** [comment]
Yes, of course. It's in 1.1.0 tag now.

Cheers.

JZ

**Comment by xini** [comment]
thanks, mate!

**Pull request merged**
